name: Generate changeset for Renovate

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Git Identity
        run: |
          git config --global user.name 'Yopem Bot'
          git config --global user.email 'github@yopem.com'
      - uses: pnpm/action-setup@v4.1.0
      - name: Run changesets-renovate
        run: bunx @scaleway/changesets-renovate
