name: "Dependabot Changesets"

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  changesets:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Dependabot Changesets
        uses: feelepxyz/dependabot-changesets@v1
